---
- hosts: database
  become: true
  tasks:
  - name: Install mariadb
    yum: 
      name: mariadb-server
      state: present
  - name: Start mariadb
    service: name=mariadb state=started enabled=yes
